name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for manual release'
        required: true
        default: 'v1.0.0'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd web
          npm ci

      - name: Build web UI
        run: |
          cd web
          npm run build

      - name: Zip resource
        run: |
          cd resources/[ruptz]
          zip -r Rup-ReportMenu.zip Rup-ReportMenu -x '*/node_modules/*' '*/.git/*' '*/.env*' '*/.vscode/*' '*/.github/*'
          mv Rup-ReportMenu.zip ../../..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Rup-ReportMenu.zip
          tag_name: ${{ github.ref_name || github.event.inputs.version }}
          name: Release ${{ github.ref_name || github.event.inputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
